# Generated by Django 4.1.7 on 2023-04-06 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(db_index=True, max_length=100, verbose_name='Название продукта')),
                ('product_calories', models.FloatField(verbose_name='Количество ккал в продукте')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_recipe', models.CharField(max_length=150, verbose_name='Название рецепта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('count_servings', models.IntegerField(blank=True, null=True, verbose_name='Количество порций')),
                ('count_calories', models.FloatField(blank=True, null=True, verbose_name='Количество ККал')),
                ('recipe_description', models.TextField(verbose_name='Описание рецепта')),
                ('need_products', models.ManyToManyField(to='main.products', verbose_name='Необходимые продукты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('Last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('First_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('Nickname', models.CharField(max_length=30, verbose_name='Никнейм пользователя')),
                ('email_user', models.EmailField(max_length=30, verbose_name='Email пользователя')),
                ('favorite_recipes', models.ManyToManyField(to='main.recipe', verbose_name='Избранные рецепты')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
