# Generated by Django 4.1.7 on 2023-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mass',
            field=models.FloatField(null=True, verbose_name='Количество в гр'),
        ),
    ]
