# Generated by Django 4.1.7 on 2023-05-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categories_alter_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='need_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время готовки (в минутах)'),
        ),
    ]
