# Generated by Django 4.1.7 on 2023-05-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recipe_need_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_user',
        ),
    ]
