# Generated by Django 4.1.7 on 2023-05-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('1', 'Завтраки'), ('2', 'Основные блюда'), ('3', 'Закуски'), ('4', 'Супы'), ('5', 'Салаты'), ('6', 'Выпечка и десерты')], default='1', max_length=150),
        ),
        migrations.DeleteModel(
            name='categories',
        ),
    ]
