# Generated by Django 4.1.7 on 2023-06-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
