# Generated by Django 4.1.7 on 2023-06-02 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_profile_favorite_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fav_recs',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Избранные рецепты'),
        ),
    ]
